authlog:
  filepath: /var/log/secure
  recent_line: 'Feb 15 15:43:35 ip-172-31-51-31 sshd[31105]: Did not receive identification
    string from 206.189.111.9 port 54002'
  recent_mod: 0
syslog:
  filepath: /var/log/messages
  recent_line: 'Feb 13 23:36:46 ip-172-31-51-31 dhclient[2244]: XMT: Solicit on eth0,
    interval 111580ms.'
  recent_mod: 0
